### ISSUE TITLE
School! 

### ISSUE THREAD

**Issue by thayea2** [LightingResearchCenter/HealthyPatterns#202]
Finally doing schools _hooray_ @thayea2 

Ask for Excel document with the organized selection tree. 
Ask for Word document containing selection process text which includes:

- School description
- Room descriptions (Classroom, Special needs classroom, Lecture hall, dorm)
- Fixture descriptions (images *NOW INCLUDED*, see below & repo)
- Target CS descriptions (Check the repo for images-- use 0.3 for special needs classroom)
- CCTs used will be: 3000 K, 4000 K, 5000 K, 6500 K

- Note: There are two descriptions for "Downlight + Wall Wash" Once for offices where the wall wash is blue and red, and one for down where wall wash stays white. Same image can be used, but please use different description.

Let's make a fun list of fixture collages for @thayea2  to make:

- [x] 1x4 Recessed linear + blue linear + wall wash
- [X] 2x2 Troffer + blue linear
- [X] Skylight panel
- [X] Cove + Downlight + Wall wash
- [X] Floor lamp + Task lamp
- [X] Flush mount + Desk luminaire
- [X] Downlight + Wall wash

**Comment by MichaelvMorrison** [comment]
Are you having fun
